//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr419
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ProdutsDetails
    {
        public int количество { get; set; }
        public string Артикул { get; set; }
        public string Наименование { get; set; }
        public string название { get; set; }
        public short Стоимость { get; set; }
        public byte Действующая_скидка { get; set; }
        public byte Размер_максимально_возможной_скидки { get; set; }
        public string Категория { get; set; }
        public string Описание { get; set; }
    }
}
