//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr419
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказы()
        {
            this.ПродукцияЗаказа = new HashSet<ПродукцияЗаказа>();
        }
    
        public int ид { get; set; }
        public System.DateTime Дата_заказа { get; set; }
        public System.DateTime Дата_доставки { get; set; }
        public int Пункт_выдачи { get; set; }
        public Nullable<int> Клиент { get; set; }
        public int Код_для_получения { get; set; }
        public int Статус_заказа { get; set; }
        public Nullable<int> Терминал { get; set; }
        public Nullable<int> СтоимостьЗаказа { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual ПунктыВыдачи ПунктыВыдачи { get; set; }
        public virtual СтатусЗаказа СтатусЗаказа { get; set; }
        public virtual Терминалы Терминалы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПродукцияЗаказа> ПродукцияЗаказа { get; set; }
    }
}
