//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr419
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поставщики
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Поставщики()
        {
            this.Заявкт = new HashSet<Заявкт>();
        }
    
        public int ид { get; set; }
        public string наименование { get; set; }
        public string ИНН { get; set; }
        public string КПП { get; set; }
        public string ФИО_директора { get; set; }
        public int представитель { get; set; }
        public string юр_адрес { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заявкт> Заявкт { get; set; }
        public virtual ПредставителиПоставщиков ПредставителиПоставщиков { get; set; }
    }
}
