//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr419
{
    using System;
    using System.Collections.Generic;
    
    public partial class Склады
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Склады()
        {
            this.ПродукцияНаСкладе = new HashSet<ПродукцияНаСкладе>();
        }
    
        public int ид { get; set; }
        public string адрес { get; set; }
        public string название { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПродукцияНаСкладе> ПродукцияНаСкладе { get; set; }
    }
}
